[package]
name = "sonic-roadtrip"
version = "0.1.0"
authors = ["W. Hunter Jones <william.hunter.jones@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = "0.7.0"
